import { type ChangeEventHandler, useState } from "react";
import Head from "next/head";

export default function Home() {
  const [selectedImage, setSelectedImage] = useState("");

  const uploadImage: ChangeEventHandler<HTMLInputElement> = (e) => {
    e.preventDefault();
    const img = e.target.files?.[0];
    if (!img) {
      return;
    }

    setSelectedImage(URL.createObjectURL(img));
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-2xl font-extrabold tracking-tight sm:text-[4rem]">
            티켓꽂이 도안 생성기
          </h1>
          <div className="flex h-[600px] w-[900px] flex-col p-4">
            {/*티켓*/}
            <div className="fles-row flex h-[calc(100%*8/10.2)] w-full hover:bg-black/20">
              {/*티켓 넣는 곳*/}
              <div className="flex h-full w-3/5 items-center justify-center bg-black/80">
                <div className="h-4/5 w-4/5 bg-black/40 [clip-path:polygon(15%_0%,100%_0,100%_82%,_85%_100%,0_100%,0%_18%)]"></div>
              </div>
              {/* 사진 넣는 곳 */}
              <div className="flex h-full w-2/5 cursor-pointer items-center justify-center">
                <input
                  type="file"
                  accept="image/jpg,impge/png,image/jpeg"
                  name="ticket_image"
                  onChange={uploadImage}
                />
                {selectedImage !== "" ? (
                  <img
                    src={selectedImage}
                    alt="티켓 사진"
                    className="h-full object-cover"
                  />
                ) : (
                  <button>클릭하여 사진 업로드</button>
                )}
              </div>
            </div>
            {/*자르는 곳*/}
            <div className="h-[calc(100%*2.2/10.2)] w-full bg-black/100"></div>
          </div>
          <p className="text-xl">
            기본 이미지 업로드 후 티켓 절취선에 맞는 색상을 선택합니다.
          </p>
          <button className="bg-mint/50 rounded-lg">
            티켓꽂이 이미지 (png) 다운로드받기
          </button>
        </div>
      </main>
    </>
  );
}
